development:
  adapter: postgresql
  encoding: unicode
  database: book_shop_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: book_shop_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: book_shop_production
  pool: 5
  username:
  password:
